name: Github Actions Example

on:
  pull_request:
  push:
    branches: 
      - master

  schedule:
    # * es un caracter especial en YAML, asique se usa un string
    - cron:  '*/1 * * * *'


jobs:
  test:
    name: Running Units Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Imprimiendo un mensaje
      echo "Hola, este es un mensaje de texto."